version: "3.1"

services:

  db:
    container_name: postgresql
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pass 
    networks:
      - zabbix_network

  zabbix_server:
    container_name: zabbix
    image: zabbix/zabbix-server-pgsql:centos-trunk
    restart: always
    networks:
      - zabbix_network

  zabbix_frontend:
    container_name: web_zabbix
    image: zabbix/zabbix-web-nginx-pgsql:centos-trunk
    restart: always
    networks:
      - zabbix_network

networks:
  zabbix_network:
    name: zabbix_network

secrets:
  postgres_pass:
    file: ./postgres_pass
